server:
  port: 80
  session:
    timeout: 3600

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: tttx
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password: tttx
  security:
    user:
      name: kevin
      password: tttx

imooc:
  security:
    browser:
#      loginPage: /demo-signIn.html
      loginType: JSON
      code:
        image:
          length: 6
          width: 100
          url: /user,/user/*
      signUpUrl: /demo-signUp.html
      signOutUrl: /demo-logout.html
    social:
      qq:
        app-id: 101364240
        app-secret: ef27b7a6ca651a3609dd47f21e385955
        providerId: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
      filterProcessingUrl: /qqLogin
    oauth2:
      clients:
        - client-id: imooc
          client-secret: imoocsecret
          accessTokenValiditySeconds: 3600
          authorizedGrantTypes: [refresh_token,password]
          scopes: [all,read,write]
        - client-id: test
          client-secret: test
          accessTokenValiditySeconds: 7200
          authorizedGrantTypes: [refresh_token,password]
          scopes: [all,read,write]



#security:
#  oauth2:
#    client:
#      client-id: imooc
#      client-secret: imoocsecret
