server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: tttx
  security:
    user:
      name: kevin
      password: tttx

imooc:
  security:
    browser:
#      loginPage: /demo-signIn.html
      loginType: JSON
    code:
      image:
        length: 6
        width: 100
        url: /user,/user/*