server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: tttx
  session:
    store-type: none
  redis:
    host: localhost
    port: 6379
    password: tttx
  security:
    user:
      name: kevin
      password: tttx

imooc:
  security:
    social:
      qq:
        app-id: 101364240
        app-secret: ef27b7a6ca651a3609dd47f21e385955
        providerId: qq
      filterProcessingUrl: /login
